name: Build only

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake
          brew install pkgconf
          brew install autoconf
          brew install automake
          brew install libtool
          brew install ninja
          brew install rename

      - name: Prepare gradle
        run: chmod +x ./gradlew

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: shaderc
        run: ./gradlew assemble[shaderc] --info --stacktrace

      - name: spirvcross
        run: ./gradlew assemble[spirvcross] --info --stacktrace

      - name: vulkan
        run: ./gradlew assemble[vulkan] --info --stacktrace

      - name: dovi
        run: ./gradlew assemble[dovi] --info --stacktrace

      - name: lcms2
        run: ./gradlew assemble[littlecms2] --info --stacktrace

      - name: dav1d
        run: ./gradlew assemble[dav1d] --info --stacktrace

      - name: placebo
        run: ./gradlew assemble[placebo] --info --stacktrace

      - name: uchardet
        run: ./gradlew assemble[uchardet] --info --stacktrace

      - name: unibreak
        run: ./gradlew assemble[unibreak] --info --stacktrace

      - name: fribidi
        run: ./gradlew assemble[fribidi] --info --stacktrace

      - name: freetype
        run: ./gradlew assemble[freetype] --info --stacktrace

      - name: harfbuzz
        run: ./gradlew assemble[harfbuzz] --info --stacktrace

      - name: mbedtls
        run: ./gradlew assemble[mbedtls] --info --stacktrace

      - name: ass
        run: ./gradlew assemble[ass] --info --stacktrace

      - name: ffmpeg
        run: ./gradlew assemble[ffmpeg] --info --stacktrace

      - name: mpv
        run: ./gradlew assemble[mpv] --info --stacktrace
